# Generated by Django 5.0.4 on 2024-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('team', models.CharField(choices=[('ElemG', "Girl's 5th and 6th"), ('MidG', "Girl's 7th and 8th"), ('VarsityG', "Girl's Varsity"), ('ElemB', "Boy's 5th and 6th"), ('MidB', "Boy's 7th and 8th"), ('VarsityB', "Boy's Varsity")], max_length=8)),
                ('position', models.CharField(choices=[('1', 'Point Guard'), ('2', 'Shooting Guard'), ('3', 'Small Forward'), ('4', 'Power Forward'), ('5', 'Center')], max_length=1)),
                ('jersey', models.IntegerField()),
            ],
        ),
    ]
