# Generated by Django 5.0.4 on 2024-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('ElemG', "Girl's 5th and 6th"), ('MidG', "Girl's 7th and 8th"), ('VarsityG', "Girl's Varsity"), ('ElemB', "Boy's 5th and 6th"), ('MidB', "Boy's 7th and 8th"), ('VarsityB', "Boy's Varsity")], max_length=8)),
                ('opponent', models.CharField(max_length=75)),
                ('team_score', models.IntegerField()),
                ('opp_score', models.IntegerField()),
                ('outcome', models.CharField(choices=[('W', 'Win'), ('L', 'Loss')], max_length=1)),
                ('date', models.DateField()),
            ],
        ),
    ]
