# Generated by Django 5.0.4 on 2024-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='s_type',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='season',
        ),
        migrations.AddField(
            model_name='stats',
            name='drill_name',
            field=models.CharField(default='Test', max_length=20),
            preserve_default=False,
        ),
    ]
