# Generated by Django 5.0.4 on 2024-04-24 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_delete_game_remove_stats_s_type_remove_stats_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='drill_name',
        ),
        migrations.CreateModel(
            name='FreeThrows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attempts', models.IntegerField()),
                ('makes', models.IntegerField()),
                ('percentage', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='ShootingDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_name', models.CharField(max_length=20)),
                ('two_taken', models.IntegerField()),
                ('two_made', models.IntegerField()),
                ('three_taken', models.IntegerField()),
                ('three_made', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.athlete')),
            ],
        ),
    ]
