# Generated by Django 5.0.4 on 2024-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_stats_drill_name_freethrows_shootingdrill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freethrows',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='freethrows',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freethrows',
            name='makes',
            field=models.IntegerField(default=0),
        ),
    ]
