# Generated by Django 5.0.4 on 2024-04-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_remove_freethrows_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
