# Generated by Django 5.0.4 on 2024-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
