# Generated by Django 5.0.4 on 2024-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_athlete_username_alter_athlete_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='freethrows',
            name='last_opp',
            field=models.CharField(default='none', max_length=4),
        ),
    ]
