# Generated by Django 5.0.4 on 2024-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_freethrows_last_opp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='position',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='freethrows',
            name='last_opp',
            field=models.CharField(max_length=4),
        ),
    ]
